import Head from "next/head";
// import Image from "next/image";
import styles from "../styles/Home.module.css";
import {
  Heading,
  Grid,
  GridItem,
  Image,
  Text,
  Box,
  Flex,
} from "@chakra-ui/react";
import { FaStar } from "react-icons/fa";
import { BiGitRepoForked } from "react-icons/bi";

const Page = ({ data }) => {
  // console.log(data.items);
  return (
    <div className={styles.container}>
      <Head>
        <title>Repo Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Heading marginBottom={20}>All Star Repositories</Heading>
        <Grid templateColumns="repeat(5, 1fr)" gap={6} textAlign="center">
          {data.items.map((repo) => (
            <GridItem w="100%" h="auto" key={repo.id} border="1px solid black">
              <Image
                src={repo.owner.avatar_url}
                alt="Image-1"
                width={200}
                height={200}
                margin="auto"
                padding="20px"
              />
              <Text>{repo.name}</Text>
              <Text>{repo.language}</Text>
              <Box padding="10px 0">
                <Flex justifyContent="space-evenly">
                  <Box>
                    <Flex>
                      <Box mt="4px" mr="2px">
                        <FaStar />
                      </Box>
                      <Box>
                        <Text>{repo.stargazers_count}</Text>
                      </Box>
                    </Flex>
                  </Box>
                  <Box>
                    <Flex>
                      <Box mt="4px" mr="2px">
                        <BiGitRepoForked />
                      </Box>
                      <Box>
                        <Text>{repo.forks_count}</Text>
                      </Box>
                    </Flex>
                  </Box>
                </Flex>
              </Box>
            </GridItem>
          ))}
        </Grid>
      </main>
    </div>
  );
};

export async function getStaticProps() {
  // Fetch data from external API
  const res = await fetch(
    `https://api.github.com/search/repositories?q=stars:%3E1+language:all`
  );
  const data = await res.json();

  // Pass data to the page via props
  return { props: { data } };
}

export default Page;
